### ISSUE TITLE
Install dependencies = error ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by remijean** [FortAwesome/react-fontawesome#237]
I can no longer execute the "yarn" command, every time Font Awesome returns this error:

```
Arguments: 
  /usr/bin/node /usr/share/yarn/bin/yarn.js

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/SmartGit/git/usr/bin:/mnt/c/Windows/System32/OpenSSH:/mnt/c/PostgreSQL/pg11/bin:/mnt/c/Users/remij/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/remij/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin

Yarn version: 
  1.15.2

Node version: 
  8.15.1

Platform: 
  linux x64

Trace: 
  Error: https://npm.fontawesome.com/@fortawesome/pro-light-svg-icons/-/pro-light-svg-icons-5.8.1.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/usr/share/yarn/lib/cli.js:130168:19)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:106:13)
      at ClientRequest.emit (events.js:208:7)
      at TLSSocket.emitTimeout (_http_client.js:721:34)
      at Object.onceWrapper (events.js:313:30)
      at emitNone (events.js:106:13)
      at TLSSocket.emit (events.js:208:7)
      at TLSSocket.Socket._onTimeout (net.js:422:8)
      at ontimeout (timers.js:498:11)

npm manifest: 
  {
    "name": "assoconnect-frontend",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
      "@fortawesome/fontawesome-svg-core": "^1.2.17",
      "@fortawesome/pro-light-svg-icons": "^5.8.1",
      "@fortawesome/pro-regular-svg-icons": "^5.8.1",
      "@fortawesome/pro-solid-svg-icons": "^5.8.1",
      "@fortawesome/react-fontawesome": "^0.1.4",
      "apollo-boost": "^0.3.1",
      "bootstrap": "^4.3.1",
      "classnames": "^2.2.6",
      "graphql": "^14.2.1",
      "graphql-tag": "^2.10.1",
      "lodash": "^4.17.11",
      "node-sass": "^4.11.0",
      "react": "^16.8.2",
      "react-animate-height": "^2.0.8",
      "react-apollo": "^2.5.5",
      "react-dom": "^16.8.2",
      "react-placeholder": "^3.0.2",
      "react-router-dom": "^5.0.0",
      "react-scripts": "3.0.0",
      "react-svg": "^9.0.4",
      "react-table": "^6.9.2",
      "reactstrap": "^8.0.0",
      "sass-extract": "^2.1.0",
      "sass-extract-js": "^0.4.0",
      "sass-extract-loader": "^1.1.0",
      "styled-components": "^4.1.3",
      "typescript": "^3.4.5",
      "uniqid": "^5.0.3"
    },
    "scripts": {
      "start": "react-scripts start",
      "build": "react-scripts build",
      "test": "react-scripts test",
      "eject": "react-scripts eject"
    },
    "eslintConfig": {
      "extends": "react-app"
    },
    "browserslist": [
      ">0.2%",
      "not dead",
      "not ie <= 11",
      "not op_mini all"
    ],
    "devDependencies": {
      "@fortawesome/fontawesome-pro": "^5.8.1",
      "@types/classnames": "^2.2.7",
      "@types/jest": "^24.0.11",
      "@types/lodash": "^4.14.123",
      "@types/node": "^12.0.0",
      "@types/react": "^16.8.4",
      "@types/react-dom": "^16.8.2",
      "@types/react-router-dom": "^4.3.1",
      "@types/react-table": "^6.7.22",
      "@types/react-test-renderer": "^16.8.1",
      "@types/reactstrap": "^8.0.1",
      "@types/styled-components": "^4.1.10",
      "@types/uniqid": "^4.1.3",
      "enzyme": "^3.9.0",
      "enzyme-adapter-react-16": "^1.12.1",
      "prettier": "^1.17.0",
      "react-test-renderer": "^16.8.3"
    },
    "prettier": {
      "singleQuote": true,
      "semi": false,
      "trailingComma": "es5"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

```

My .npmrc file is configured correctly:

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

**Comment by GwendolynWitecki** [comment]
I have been experiencing a similar issue. I would be very interested to know about this.

**Comment by GwendolynWitecki** [comment]
![image](https://user-images.githubusercontent.com/50336941/57813302-9ea78580-773d-11e9-9041-c1da9789ff1e.png)

When I removed my node_modules folder and did another yarn install, I found I got this error. I am not directly referencing transformation-matrix-js@2.7.6 directly in my dependencies. My best guess is that either fontawesome-svg-core or react-fontawesome has this file as a dependency, but it is no longer supported so when yarn goes to retrieve it, it's not there to be retrieved.

**Comment by remijean** [comment]
I found a temporary "solution", I delete the lines of my package.json:

"@fortawesome/pro-light-svg-icons": "^5.8.2",
"@fortawesome/pro-regular-svg-icons": "^5.8.2",
"@fortawesome/pro-solid-svg-icons": "^5.8.2",

I run a yarn, it works, then I restart the installation of three libraries with a yarn add.

Unfortunately, this is not a long-term solution...

**Comment by robmadole** [comment]
@remijean we are not having any service interruptions currently for that npm.fontawesome.com service. Please check you network configuration or connectivity.

@GwendolynWitecki none of our packages use `transformation-matrix-js`. Note that the dependency chain points back to `webfont-webpack-plugin`.

**Comment by remijean** [comment]
@robmadole this problem is present on multiple networks and multiple computers. We also have this problem from our Azure server.

Four of our developers have the same problem, so there is a real problem, this issue can not be closed. Do you need more information?

**Comment by GwendolynWitecki** [comment]
I got a different error when I removed my node_modules folder and attempted a new yarn install.

![image](https://user-images.githubusercontent.com/50336941/58041557-61a90d80-7b06-11e9-8343-7d47b3fa51c3.png)

**Comment by remijean** [comment]
@GwendolynWitecki I had the same error !

**Comment by remijean** [comment]
@robmadole my network connectivity is good but the problem is always present :

![image](https://user-images.githubusercontent.com/4329231/58266502-0c793000-7d82-11e9-8ffa-1021ddb80483.png)

**Comment by robmadole** [comment]
@remijean can you try the workaround mentioned here?

https://github.com/yarnpkg/yarn/issues/5540#issuecomment-374069461

**Comment by robclancy** [comment]
CI completely randomly does this. A super long timeout isn't useful because we don't want CI taking this long. I have it running now and it needed almost the entire 10 minutes. 

I guess the other workaround posted here might be enough, where before `yarn` I will remove the font awesome packages and then `yarn add` after. But why would `yarn add` have no issue with it and `yarn install` does?

**Comment by robclancy** [comment]
This must be a gitlab runner issue. I did all their defaults using their own system to build it so makes no sense... and it also randomly works. Wondering if other people here are using gitlab-ci. With the timeout workaround we just timeout the CI after 20 minutes now instead.

**Comment by remijean** [comment]
@robmadole Sorry for the late reply. The bug has not appeared since early June... I would test https://github.com/yarnpkg/yarn/issues/5540#issuecomment-374069461 if the bug reappears.

Thanks you.

**Comment by robclancy** [comment]
A network timeout that is super long does not help. I don't want to wait 10 minutes for the install step of our CI. When I increased this stuff usually we just hit a different timeout from CI anyway.

When I posted this here this problem was persistent, in the past was random. Then it became random again. I don't know what it is like now since I'm on holidays. 

I think in future we will just bundle dependencies for this instead, since that will be 100% reliable and just when we update we do it manually.
