### ISSUE TITLE
Invalid Tar File Error on (re)Installation

### ISSUE THREAD

**Issue by geoffdavis92** [FortAwesome/react-fontawesome#316]
**Describe the bug**
Re-installing node packages in a Gatsby project, and getting an error that the react-fontawesome's tarball is not valid.

**Reproducible test case**
Project is private, but here's the stack trace from my `yarn-error.log` file

```
Error: https://npm.fontawesome.com/@fortawesome/react-fontawesome/-/0.1.8/react-fontawesome-0.1.8.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
      at BlockStream.emit (events.js:203:13)
      at BlockStream._emitChunk (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.flush (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:70:8)
      at BlockStream.end (/usr/local/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:66:8)
      at Extract.Parse.end (/usr/local/lib/node_modules/yarn/node_modules/tar/lib/parse.js:86:23)
      at UnpackStream.onend (_stream_readable.js:682:10)
      at Object.onceWrapper (events.js:291:20)
```

**Expected behavior**
Expected react-fontawesome package to be installed successfully. 

**Desktop (please complete the following information):**

(not a browser issue)

**Comment by robmadole** [comment]
@geoffdavis92 a couple of things to check. Are you behind a firewall that could be messing with the request? Is it possible that your `yarn.lock` has the wrong hash? (Try deleting the `yarn.lock`). You might also try `npm` instead of Yarn.

**Comment by geoffdavis92** [comment]
@robmadole Thanks for the reply; I'm not behind a firewall (I had tried this on 2 different networks) so that wouldn't be the case.

I'll try removing `yarn.lock` 👍 

I had perviously tried `npm` but got the same result, including removing `node_modules` and re-installing, then an `npm rebulid` attempt. All these yielded the same error.
